// Karim 2026-07-11 : liste de nationalités (gentilés FR) pour un choix par liste
// plutôt qu'une saisie libre. UE/EEE/Suisse en tête (droit au travail direct),
// puis le reste. Utilisée en <datalist> (choix + saisie libre tolérée).

export const EU_EEA_CH_NATIONALITIES = [
  "Belge",
  "Française",
  "Allemande",
  "Néerlandaise",
  "Luxembourgeoise",
  "Italienne",
  "Espagnole",
  "Portugaise",
  "Irlandaise",
  "Autrichienne",
  "Grecque",
  "Polonaise",
  "Roumaine",
  "Bulgare",
  "Hongroise",
  "Tchèque",
  "Slovaque",
  "Slovène",
  "Croate",
  "Danoise",
  "Suédoise",
  "Finlandaise",
  "Estonienne",
  "Lettone",
  "Lituanienne",
  "Maltaise",
  "Chypriote",
  "Islandaise",
  "Norvégienne",
  "Liechtensteinoise",
  "Suisse",
];

export const OTHER_NATIONALITIES = [
  "Marocaine",
  "Algérienne",
  "Tunisienne",
  "Turque",
  "Congolaise (RDC)",
  "Camerounaise",
  "Ivoirienne",
  "Sénégalaise",
  "Guinéenne",
  "Malienne",
  "Nigériane",
  "Ghanéenne",
  "Rwandaise",
  "Burundaise",
  "Égyptienne",
  "Libanaise",
  "Syrienne",
  "Irakienne",
  "Iranienne",
  "Afghane",
  "Pakistanaise",
  "Indienne",
  "Bangladaise",
  "Sri-lankaise",
  "Népalaise",
  "Chinoise",
  "Philippine",
  "Vietnamienne",
  "Thaïlandaise",
  "Indonésienne",
  "Brésilienne",
  "Argentine",
  "Colombienne",
  "Vénézuélienne",
  "Péruvienne",
  "Équatorienne",
  "Bolivienne",
  "Mexicaine",
  "Américaine (USA)",
  "Canadienne",
  "Britannique",
  "Ukrainienne",
  "Russe",
  "Serbe",
  "Bosnienne",
  "Albanaise",
  "Kosovare",
  "Macédonienne",
  "Moldave",
  "Géorgienne",
  "Arménienne",
  "Azerbaïdjanaise",
  "Sud-africaine",
  "Angolaise",
  "Mauritanienne",
  "Somalienne",
  "Soudanaise",
  "Éthiopienne",
  "Érythréenne",
  "Kényane",
  "Tanzanienne",
  "Ougandaise",
  "Palestinienne",
  "Jordanienne",
  "Israélienne",
  "Apatride",
];

export const ALL_NATIONALITIES = [...EU_EEA_CH_NATIONALITIES, ...OTHER_NATIONALITIES];
